[colors]
[colors.primary]
background = "#20242E"
foreground = "#D7DCE1"

[colors.normal]
black   = "#20242E"
red     = "#c07a93"
green   = "#2f9f79"
yellow  = "#62a658"
blue    = "#82a5e4"
magenta = "#9b7fd9"
cyan    = "#00acdc"
white   = "#D7DCE1"

[colors.bright]
black   = "#72747b"
red     = "#ed9bbb"
green   = "#4cc895"
yellow  = "#72ca66"
blue    = "#99c4ff"
magenta = "#c39fff"
cyan    = "#00cfff"
white   = "#eff6ff"

[colors.cursor]
text   = "#20242E"
cursor = "#D7DCE1"
