# UI Colors (extended)
accent = "#82a5e4"
cursor = "#D7DCE1"

# Primary colors
foreground = "#D7DCE1"
background = "#20242E"

# Selection colors
selection_foreground = "#20242E"
selection_background = "#D7DCE1"

# Normal colors (ANSI 0-7)
color0 = "#20242E"
color1 = "#c07a93"
color2 = "#2f9f79"
color3 = "#62a658"
color4 = "#82a5e4"
color5 = "#9b7fd9"
color6 = "#00acdc"
color7 = "#D7DCE1"

# Bright colors (ANSI 8-15)
color8 = "#72747b"
color9 = "#ed9bbb"
color10 = "#4cc895"
color11 = "#72ca66"
color12 = "#99c4ff"
color13 = "#c39fff"
color14 = "#00cfff"
color15 = "#eff6ff"
