background = #20242E
foreground = #D7DCE1

palette = 0 = #20242E
palette = 1 = #c07a93
palette = 2 = #2f9f79
palette = 3 = #62a658
palette = 4 = #82a5e4
palette = 5 = #9b7fd9
palette = 6 = #00acdc
palette = 7 = #D7DCE1
palette = 8 = #72747b
palette = 9 = #ed9bbb
palette = 10 = #4cc895
palette = 11 = #72ca66
palette = 12 = #99c4ff
palette = 13 = #c39fff
palette = 14 = #00cfff
palette = 15 = #eff6ff

selection-background = #D7DCE1
selection-foreground = #20242E
cursor-color = #D7DCE1
cursor-text = #20242E
