# ~/.config/hypr/hyprlauncher.conf

# Default mode: all (apps + files), apps, files, scripts
mode = all

# Appearance
font = "JetBrainsMono Nerd Font 12"
prompt = "➜"
background = #1d2021f2
foreground = #ffffff
border = #c0caf5
selection = #C0A176

# Size/position
width = 600
height = 400
anchor = center

# Behavior
case_sensitive = false
fuzzy_match = true
show_icons = true
