general {
    lock_cmd = pidof hyprlock || hyprlock          # Prevents multiple instances
    before_sleep_cmd = hypr-pre-sleep && loginctl lock-session
    after_sleep_cmd = hypr-post-sleep && hyprctl dispatch dpms on
}
