general {
    hide_cursor = true
    immediate_render = true
}

background {
    monitor =
    path = /home/bldnwine/Pictures/FrMJvnqWIAEJg_l.jpeg
    blur_passes = 0
    blur_size = 7
}

input-field {
    monitor =
    size = 250, 50
    position = 0, -20
    halign = center
    valign = center
    inner_color = rgba(0, 0, 0, 0)
    outer_color = rgb(AEAFAF)
    outline_thickness = 2
    check_color = rgb(131, 162, 152)
    font_color = rgb(FFFFFF)
}
animation = fade, 0, 0, default
