# UI Colors (extended)
accent = "#ab97dc"
cursor = "#F0CF8E"

# Primary colors
foreground = "#F0CF8E"
background = "#0E141E"

# Selection colors
selection_foreground = "#0E141E"
selection_background = "#F0CF8E"

# Normal colors (ANSI 0-7)
color0 = "#0E141E"
color1 = "#a8733f"
color2 = "#85852c"
color3 = "#ac9016"
color4 = "#ab97dc"
color5 = "#c1678e"
color6 = "#1cb685"
color7 = "#F0CF8E"

# Bright colors (ANSI 8-15)
color8 = "#6c6f75"
color9 = "#d29751"
color10 = "#a6a527"
color11 = "#d2ae00"
color12 = "#ccb4ff"
color13 = "#ef86b8"
color14 = "#00dc9e"
color15 = "#faf5ea"
