background = #0E141E
foreground = #F0CF8E

palette = 0 = #0E141E
palette = 1 = #a8733f
palette = 2 = #85852c
palette = 3 = #ac9016
palette = 4 = #ab97dc
palette = 5 = #c1678e
palette = 6 = #1cb685
palette = 7 = #F0CF8E
palette = 8 = #6c6f75
palette = 9 = #d29751
palette = 10 = #a6a527
palette = 11 = #d2ae00
palette = 12 = #ccb4ff
palette = 13 = #ef86b8
palette = 14 = #00dc9e
palette = 15 = #faf5ea

selection-background = #F0CF8E
selection-foreground = #0E141E
cursor-color = #F0CF8E
cursor-text = #0E141E
