$color = rgba(14, 20, 30, 1)
$inner_color = rgba(14, 20, 30, 0.66)
$outer_color = rgba(193, 103, 142, 1)
$font_color = rgba(240, 207, 142, 1)
$placeholder_color = rgba(240, 207, 142, 0.7)
$check_color = rgba(28, 182, 133, 1)
