# Aether Hyprland Theme
# Source this file in your hyprland.conf: source = ~/.config/aether/theme/hyprland.conf

$background = #0E141E
$foreground = #F0CF8E
$black = #0E141E
$red = #a8733f
$green = #85852c
$yellow = #ac9016
$blue = #ab97dc
$magenta = #c1678e
$cyan = #1cb685
$white = #F0CF8E
$bright_black = #6c6f75
$bright_red = #d29751
$bright_green = #a6a527
$bright_yellow = #d2ae00
$bright_blue = #ccb4ff
$bright_magenta = #ef86b8
$bright_cyan = #00dc9e
$bright_white = #faf5ea

# Border colors
$border_active = #ab97dc
$border_inactive = #6c6f75
