#!/usr/bin/env bash
# ==============================================================================
# setup.sh - Automated Nix & nics Setup for Arch Linux
# Configures multi-user daemon, flakes, unstable + stable channels, and shell.
# ==============================================================================

set -euo pipefail

# Script directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Color formatting
if [ -t 1 ]; then
  BOLD=$'\033[1m'
  DIM=$'\033[2m'
  RED=$'\033[0;31m'
  GREEN=$'\033[0;32m'
  YELLOW=$'\033[0;33m'
  BLUE=$'\033[0;34m'
  CYAN=$'\033[0;36m'
  NC=$'\033[0m'
else
  BOLD=""
  DIM=""
  RED=""
  GREEN=""
  YELLOW=""
  BLUE=""
  CYAN=""
  NC=""
fi

log_step()    { echo -e "\n${BLUE}${BOLD}==>${NC} ${BOLD}$*${NC}"; }
log_info()    { echo -e "${CYAN}${BOLD}[INFO]${NC} $*"; }
log_success() { echo -e "${GREEN}${BOLD}[OK]${NC} $*"; }
log_warn()    { echo -e "${YELLOW}${BOLD}[WARN]${NC} $*" >&2; }
log_error()   { echo -e "${RED}${BOLD}[ERROR]${NC} $*" >&2; }

# Privilege elevation and user context handler
SUDO=""
TARGET_USER="${SUDO_USER:-$USER}"
TARGET_HOME="$(getent passwd "$TARGET_USER" 2>/dev/null | cut -d: -f6 || echo "$HOME")"

if [ "$EUID" -ne 0 ]; then
  if command -v sudo >/dev/null 2>&1; then
    SUDO="sudo"
  elif command -v pkexec >/dev/null 2>&1; then
    SUDO="pkexec"
  else
    log_error "Root privileges are required to configure Nix daemon. Please install sudo or pkexec."
    exit 1
  fi
fi

# Run a command under the target non-root user context
run_as_target_user() {
  if [ "$EUID" -eq 0 ] && [ "$TARGET_USER" != "root" ]; then
    if command -v runuser >/dev/null 2>&1; then
      runuser -u "$TARGET_USER" -- "$@"
    elif command -v su >/dev/null 2>&1; then
      su - "$TARGET_USER" -c "$*"
    else
      "$@"
    fi
  else
    "$@"
  fi
}

echo -e "${CYAN}${BOLD}"
cat << "EOF"
  _  _ _       ___      _               
 | \| (_)_ __ / __| ___| |_ _  _ _ __  
 | .` | \ \ / \__ \/ -_)  _| || | '_ \ 
 |_|\_|_/_\_\ |___/\___|\__|\_,_| .__/ 
                                |_|    
EOF
echo -e "${NC}Nix Package Manager & 'nics' CLI Setup for Arch Linux"
echo -e "Target user: ${BOLD}$TARGET_USER${NC} | Home: ${BOLD}$TARGET_HOME${NC}\n"

# ------------------------------------------------------------------------------
# 1. Install Nix Package via Pacman
# ------------------------------------------------------------------------------
log_step "1/6 Installing Nix package via pacman..."

if ! command -v pacman >/dev/null 2>&1; then
  log_error "This script is designed for Arch Linux (pacman not found)."
  exit 1
fi

if pacman -Qi nix >/dev/null 2>&1; then
  log_success "Nix package is already installed."
else
  $SUDO pacman -S --needed --noconfirm nix
  log_success "Nix package installed successfully."
fi

# ------------------------------------------------------------------------------
# 2. Configure /etc/nix/nix.conf
# ------------------------------------------------------------------------------
log_step "2/6 Configuring Nix daemon (/etc/nix/nix.conf)..."

$SUDO mkdir -p /etc/nix

TMP_NIX_CONF=$(mktemp)
cat << 'EOF' > "$TMP_NIX_CONF"
# Nix daemon configuration generated by nics setup
build-users-group = nixbld
experimental-features = nix-command flakes
trusted-users = root @wheel
max-jobs = auto
auto-optimise-store = true
EOF

$SUDO cp "$TMP_NIX_CONF" /etc/nix/nix.conf
$SUDO chmod 644 /etc/nix/nix.conf
rm -f "$TMP_NIX_CONF"
log_success "/etc/nix/nix.conf configured with Flakes, trusted-users (@wheel), and multi-core jobs."

# ------------------------------------------------------------------------------
# 3. Enable Systemd Socket Activation (On-Demand Zero-RAM Startup)
# ------------------------------------------------------------------------------
log_step "3/6 Enabling systemd on-demand socket activation (nix-daemon.socket)..."

$SUDO systemctl enable --now nix-daemon.socket
$SUDO systemctl restart nix-daemon.socket

# Wait for daemon socket readiness
log_info "Synchronizing with Nix daemon socket..."
for i in {1..30}; do
  if [ -S "/nix/var/nix/daemon-socket/socket" ] || [ -e "/nix/var/nix/daemon-socket/socket" ]; then
    break
  fi
  sleep 0.1
done
log_success "nix-daemon.service is active and responsive."

# ------------------------------------------------------------------------------
# 4. Configure Shell Environment Integration
# ------------------------------------------------------------------------------
log_step "4/6 Configuring shell environment integration..."

# Ensure profile script is sourced in current execution context
if [ -e '/etc/profile.d/nix-daemon.sh' ]; then
  # shellcheck source=/dev/null
  . '/etc/profile.d/nix-daemon.sh'
elif [ -e '/etc/profile.d/nix.sh' ]; then
  # shellcheck source=/dev/null
  . '/etc/profile.d/nix.sh'
fi

inject_shell_config() {
  local rc_file="$1"
  local marker="# === NIX & NICS ENVIRONMENT LOADER ==="

  if [ -f "$rc_file" ]; then
    if grep -qF "$marker" "$rc_file"; then
      log_success "Environment already configured in $rc_file."
    else
      cat << 'EOF' >> "$rc_file"

# === NIX & NICS ENVIRONMENT LOADER ===
if [ -d "$HOME/.local/bin" ] && case ":$PATH:" in *":$HOME/.local/bin:"*) false;; *) true;; esac; then
  export PATH="$HOME/.local/bin:$PATH"
fi

if [ -e '/etc/profile.d/nix-daemon.sh' ]; then
  . '/etc/profile.d/nix-daemon.sh'
elif [ -e '/etc/profile.d/nix.sh' ]; then
  . '/etc/profile.d/nix.sh'
elif [ -e "$HOME/.nix-profile/etc/profile.d/nix.sh" ]; then
  . "$HOME/.nix-profile/etc/profile.d/nix.sh"
fi

# Desktop application integration for Nix GUI apps
if [ -d "$HOME/.nix-profile/share" ]; then
  case ":${XDG_DATA_DIRS:-/usr/local/share:/usr/share}:" in
    *":$HOME/.nix-profile/share:"*) ;;
    *) export XDG_DATA_DIRS="$HOME/.nix-profile/share:${XDG_DATA_DIRS:-/usr/local/share:/usr/share}" ;;
  esac
fi
# =====================================
EOF
      log_success "Added Nix & nics environment loader to $rc_file."
    fi
  fi
}

inject_shell_config "$TARGET_HOME/.bashrc"
if [ -f "$TARGET_HOME/.zshrc" ]; then
  inject_shell_config "$TARGET_HOME/.zshrc"
fi

# ------------------------------------------------------------------------------
# 5. Initialize Channels & Flake Registries (Unstable + Stable)
# ------------------------------------------------------------------------------
log_step "5/6 Initializing Channels & Flake Registries for $TARGET_USER..."

log_info "Configuring unstable channel as default nixpkgs..."
run_as_target_user nix-channel --add https://channels.nixos.org/nixpkgs-unstable nixpkgs
run_as_target_user nix-channel --add https://channels.nixos.org/nixos-24.11 stable

log_info "Updating channels (this may take a moment)..."
run_as_target_user nix-channel --update || log_warn "Channel update completed with warnings."

log_info "Configuring Flake registries for fast command evaluation..."
run_as_target_user nix registry add nixpkgs github:NixOS/nixpkgs/nixpkgs-unstable
run_as_target_user nix registry add nixpkgs-unstable github:NixOS/nixpkgs/nixpkgs-unstable
run_as_target_user nix registry add nixpkgs-stable github:NixOS/nixpkgs/nixos-24.11
log_success "Channels and Flake registries initialized (nixpkgs -> unstable, nixpkgs-stable -> 24.11 stable)."

# ------------------------------------------------------------------------------
# 6. Install & Symlink 'nics' CLI Wrapper
# ------------------------------------------------------------------------------
log_step "6/6 Installing 'nics' CLI wrapper..."

chmod +x "$SCRIPT_DIR/bin/nics"
mkdir -p "$TARGET_HOME/.local/bin"
ln -sf "$SCRIPT_DIR/bin/nics" "$TARGET_HOME/.local/bin/nics"

if [ "$EUID" -eq 0 ] && [ "$TARGET_USER" != "root" ]; then
  chown -h "$TARGET_USER:$(id -gn "$TARGET_USER")" "$TARGET_HOME/.local/bin/nics" 2>/dev/null || true
fi

log_success "'nics' CLI symlinked to $TARGET_HOME/.local/bin/nics."

# ------------------------------------------------------------------------------
# Completion & Diagnostic
# ------------------------------------------------------------------------------
echo ""
echo -e "${GREEN}${BOLD}======================================================${NC}"
echo -e "${GREEN}${BOLD}  Setup Complete! Nix & nics are ready to use.       ${NC}"
echo -e "${GREEN}${BOLD}======================================================${NC}\n"

echo -e "To activate the environment in your current shell, run:"
echo -e "  ${CYAN}${BOLD}source ~/.bashrc${NC}\n"

echo -e "Quick Usage Examples:"
echo -e "  ${BOLD}nics install <pkg>${NC}         Install from unstable (default)"
echo -e "  ${BOLD}nics install --stable <pkg>${NC}Install from stable release"
echo -e "  ${BOLD}nics gl <gui-app>${NC}          Run GUI applications with GPU acceleration"
echo -e "  ${BOLD}nics check${NC}                 Check for available package updates"
echo -e "  ${BOLD}nics update${NC}                Upgrade installed packages"
echo -e "  ${BOLD}nics rollback${NC}              Undo previous update"
echo -e "  ${BOLD}nics list${NC}                  List installed packages"
echo -e "  ${BOLD}nics doctor${NC}                Run health check diagnostic\n"
