-- Aether Neovim Colorscheme
-- Generated by Aether theming app
-- Usage: dofile(vim.fn.expand("~/.config/aether/theme/neovim.lua"))

local highlights = {
    Normal = { fg = "{foreground}", bg = "{background}" },
    NormalFloat = { fg = "{foreground}", bg = "{background}" },
    FloatBorder = { fg = "{blue}", bg = "{background}" },
    Cursor = { fg = "{background}", bg = "{foreground}" },
    CursorLine = { bg = "{bright_black}" },
    CursorColumn = { bg = "{bright_black}" },
    LineNr = { fg = "{bright_black}" },
    CursorLineNr = { fg = "{foreground}", bold = true },
    
    Comment = { fg = "{bright_black}", italic = true },
    
    Constant = { fg = "{bright_red}" },
    String = { fg = "{green}" },
    Number = { fg = "{bright_red}" },
    Boolean = { fg = "{bright_red}" },
    Float = { fg = "{bright_red}" },
    
    Identifier = { fg = "{blue}" },
    Function = { fg = "{cyan}" },
    Variable = { fg = "{foreground}" },
    
    Statement = { fg = "{magenta}" },
    Conditional = { fg = "{magenta}" },
    Repeat = { fg = "{magenta}" },
    Label = { fg = "{magenta}" },
    Operator = { fg = "{cyan}" },
    Keyword = { fg = "{magenta}" },
    Exception = { fg = "{magenta}" },
    
    PreProc = { fg = "{yellow}" },
    Include = { fg = "{magenta}" },
    Define = { fg = "{magenta}" },
    Macro = { fg = "{magenta}" },
    PreCondit = { fg = "{yellow}" },
    
    Type = { fg = "{yellow}" },
    StorageClass = { fg = "{yellow}" },
    Structure = { fg = "{yellow}" },
    Typedef = { fg = "{yellow}" },
    
    Special = { fg = "{cyan}" },
    SpecialChar = { fg = "{cyan}" },
    Tag = { fg = "{red}" },
    Delimiter = { fg = "{foreground}" },
    SpecialComment = { fg = "{bright_black}" },
    Debug = { fg = "{red}" },
    
    Title = { fg = "{cyan}", bold = true },
    Bold = { bold = true },
    Italic = { italic = true },
    Underlined = { underline = true },
    Strike = { strikethrough = true },
    
    Error = { fg = "{red}" },
    Warning = { fg = "{yellow}" },
    Info = { fg = "{blue}" },
    Hint = { fg = "{cyan}" },
    
    -- Git signs
    GitSignsAdd = { fg = "{green}" },
    GitSignsChange = { fg = "{yellow}" },
    GitSignsDelete = { fg = "{red}" },
    
    -- Telescope
    TelescopeNormal = { fg = "{foreground}", bg = "{background}" },
    TelescopeBorder = { fg = "{blue}", bg = "{background}" },
    TelescopePromptNormal = { fg = "{foreground}", bg = "{background}" },
    TelescopePromptBorder = { fg = "{blue}", bg = "{background}" },
    TelescopeSelection = { fg = "{foreground}", bg = "{bright_black}" },
    TelescopeSelectionCaret = { fg = "{blue}", bg = "{bright_black}" },
    
    -- Neotree
    NeoTreeNormal = { fg = "{foreground}", bg = "{background}" },
    NeoTreeNormalNC = { fg = "{foreground}", bg = "{background}" },
    NeoTreeFloatBorder = { fg = "{blue}", bg = "{background}" },
    
    -- Statusline
    StatusLine = { fg = "{foreground}", bg = "{bright_black}" },
    StatusLineNC = { fg = "{bright_black}", bg = "{background}" },
    StatusLineFill = { bg = "{background}" },
    StatusLineMode = { fg = "{background}", bg = "{blue}", bold = true },
    
    -- Tabline
    TabLine = { fg = "{foreground}", bg = "{background}" },
    TabLineFill = { bg = "{background}" },
    TabLineSel = { fg = "{background}", bg = "{blue}" },
    
    -- WinBar
    WinBar = { fg = "{foreground}", bg = "{background}" },
    WinBarNC = { fg = "{bright_black}", bg = "{background}" },
    
    -- Pmenu
    Pmenu = { fg = "{foreground}", bg = "{bright_black}" },
    PmenuSel = { fg = "{background}", bg = "{blue}" },
    PmenuSbar = { bg = "{bright_black}" },
    PmenuThumb = { bg = "{blue}" },
    
    -- QuickFix
    QfTodo = { fg = "{yellow}" },
    QfFile = { fg = "{blue}" },
    
    -- Treesitter
    ["@comment"] = { fg = "{bright_black}", italic = true },
    ["@variable"] = { fg = "{foreground}" },
    ["@variable.builtin"] = { fg = "{magenta}" },
    ["@constant"] = { fg = "{bright_red}" },
    ["@constant.builtin"] = { fg = "{bright_red}" },
    ["@string"] = { fg = "{green}" },
    ["@string.escape"] = { fg = "{cyan}" },
    ["@number"] = { fg = "{bright_red}" },
    ["@boolean"] = { fg = "{bright_red}" },
    ["@type"] = { fg = "{yellow}" },
    ["@type.builtin"] = { fg = "{yellow}" },
    ["@attribute"] = { fg = "{cyan}" },
    ["@function"] = { fg = "{cyan}" },
    ["@function.builtin"] = { fg = "{cyan}" },
    ["@function.call"] = { fg = "{cyan}" },
    ["@keyword"] = { fg = "{magenta}" },
    ["@keyword.function"] = { fg = "{magenta}" },
    ["@keyword.operator"] = { fg = "{magenta}" },
    ["@operator"] = { fg = "{cyan}" },
    ["@punctuation"] = { fg = "{foreground}" },
    ["@punctuation.delimiter"] = { fg = "{foreground}" },
    ["@punctuation.bracket"] = { fg = "{foreground}" },
    ["@tag"] = { fg = "{red}" },
    ["@tag.attribute"] = { fg = "{cyan}" },
    ["@tag.delimiter"] = { fg = "{foreground}" },
    ["@namespace"] = { fg = "{yellow}" },
    ["@label"] = { fg = "{blue}" },
    
    -- Diagnostic
    DiagnosticError = { fg = "{red}" },
    DiagnosticWarn = { fg = "{yellow}" },
    DiagnosticInfo = { fg = "{blue}" },
    DiagnosticHint = { fg = "{cyan}" },
    DiagnosticUnderlineError = { sp = "{red}", underline = true },
    DiagnosticUnderlineWarn = { sp = "{yellow}", underline = true },
    DiagnosticUnderlineInfo = { sp = "{blue}", underline = true },
    DiagnosticUnderlineHint = { sp = "{cyan}", underline = true },
    
    -- LSP
    LspReferenceText = { bg = "{bright_black}" },
    LspReferenceRead = { bg = "{bright_black}" },
    LspReferenceWrite = { bg = "{bright_black}" },
    LspSignatureActiveParameter = { bg = "{bright_black}" },
    
    -- Vim matchit
    MatchParen = { fg = "{background}", bg = "{cyan}" },
    Search = { fg = "{background}", bg = "{yellow}" },
    IncSearch = { fg = "{background}", bg = "{yellow}" },
    Substitute = { fg = "{background}", bg = "{green}" },
}

-- Apply highlights
for group, opts in pairs(highlights) do
    vim.api.nvim_set_hl(0, group, opts)
end
