[colors]
[colors.primary]
background = "#0d0808"
foreground = "#B4B2A8"

[colors.normal]
black   = "#0d0808"
red     = "#ab734b"
green   = "#8a7832"
yellow  = "#88793c"
blue    = "#6289A7"
magenta = "#ae6c38"
cyan    = "#6E93AC"
white   = "#B4B2A8"

[colors.bright]
black   = "#636b67"
red     = "#d69661"
green   = "#b09d3d"
yellow  = "#ae9e4b"
blue    = "#83aed4"
magenta = "#da8f4a"
cyan    = "#8fb8d8"
white   = "#d2d0c4"

[colors.cursor]
text   = "#0d0808"
cursor = "#B4B2A8"
