background = #161616
foreground = #ddd5d5

palette = 0 = #161616
palette = 1 = #a68282
palette = 2 = #8a8aad
palette = 3 = #b39393
palette = 4 = #ba9c9c
palette = 5 = #bfa6a6
palette = 6 = #c6afaf
palette = 7 = #ddd5d5
palette = 8 = #897676
palette = 9 = #cdb7b7
palette = 10 = #bfbfd4
palette = 11 = #dac8c8
palette = 12 = #e0d1d1
palette = 13 = #e6dada
palette = 14 = #ece5e5
palette = 15 = #ddd5d5

selection-background = #ddd5d5
selection-foreground = #161616
cursor-color = #ddd5d5
cursor-text = #161616
