background = #121212
foreground = #ffffff

palette = 0 = #121212
palette = 1 = #b96564
palette = 2 = #9f7f4c
palette = 3 = #aa8852
palette = 4 = #4faa50
palette = 5 = #9b7b4b
palette = 6 = #9b9b4b
palette = 7 = #ffffff
palette = 8 = #9e9e9e
palette = 9 = #e78684
palette = 10 = #bd9657
palette = 11 = #c19d64
palette = 12 = #95ff9b
palette = 13 = #bb9254
palette = 14 = #bbbb54
palette = 15 = #ffffff

selection-background = #ffffff
selection-foreground = #121212
cursor-color = #ffffff
cursor-text = #121212
