background = #0d0808
foreground = #B4B2A8

palette = 0 = #0d0808
palette = 1 = #ab734b
palette = 2 = #8a7832
palette = 3 = #88793c
palette = 4 = #6289A7
palette = 5 = #ae6c38
palette = 6 = #6E93AC
palette = 7 = #B4B2A8
palette = 8 = #636b67
palette = 9 = #d69661
palette = 10 = #b09d3d
palette = 11 = #ae9e4b
palette = 12 = #83aed4
palette = 13 = #da8f4a
palette = 14 = #8fb8d8
palette = 15 = #d2d0c4

selection-background = #B4B2A8
selection-foreground = #0d0808
cursor-color = #B4B2A8
cursor-text = #0d0808
