$color = rgba(13, 8, 8, 1)
$inner_color = rgba(13, 8, 8, 0.66)
$outer_color = rgba(174, 108, 56, 1)
$font_color = rgba(180, 178, 168, 1)
$placeholder_color = rgba(180, 178, 168, 0.7)
$check_color = rgba(110, 147, 172, 1)
