# Aether Hyprland Theme
# Source this file in your hyprland.conf: source = ~/.config/aether/theme/hyprland.conf

$background = #121212
$foreground = #ffffff
$black = #121212
$red = #b96564
$green = #9f7f4c
$yellow = #aa8852
$blue = #4faa50
$magenta = #9b7b4b
$cyan = #9b9b4b
$white = #ffffff
$bright_black = #9e9e9e
$bright_red = #e78684
$bright_green = #bd9657
$bright_yellow = #c19d64
$bright_blue = #95ff9b
$bright_magenta = #bb9254
$bright_cyan = #bbbb54
$bright_white = #ffffff

# Border colors
$border_active = #4faa50
$border_inactive = #9e9e9e
