-- Aether Neovim Colorscheme
-- Generated by Aether theming app
-- Usage: dofile(vim.fn.expand("~/.config/aether/theme/neovim.lua"))

local highlights = {
    Normal = { fg = "#B4B2A8", bg = "#0d0808" },
    NormalFloat = { fg = "#B4B2A8", bg = "#0d0808" },
    FloatBorder = { fg = "#6289A7", bg = "#0d0808" },
    Cursor = { fg = "#0d0808", bg = "#B4B2A8" },
    CursorLine = { bg = "#636b67" },
    CursorColumn = { bg = "#636b67" },
    LineNr = { fg = "#636b67" },
    CursorLineNr = { fg = "#B4B2A8", bold = true },
    
    Comment = { fg = "#636b67", italic = true },
    
    Constant = { fg = "#d69661" },
    String = { fg = "#8a7832" },
    Number = { fg = "#d69661" },
    Boolean = { fg = "#d69661" },
    Float = { fg = "#d69661" },
    
    Identifier = { fg = "#6289A7" },
    Function = { fg = "#6E93AC" },
    Variable = { fg = "#B4B2A8" },
    
    Statement = { fg = "#ae6c38" },
    Conditional = { fg = "#ae6c38" },
    Repeat = { fg = "#ae6c38" },
    Label = { fg = "#ae6c38" },
    Operator = { fg = "#6E93AC" },
    Keyword = { fg = "#ae6c38" },
    Exception = { fg = "#ae6c38" },
    
    PreProc = { fg = "#88793c" },
    Include = { fg = "#ae6c38" },
    Define = { fg = "#ae6c38" },
    Macro = { fg = "#ae6c38" },
    PreCondit = { fg = "#88793c" },
    
    Type = { fg = "#88793c" },
    StorageClass = { fg = "#88793c" },
    Structure = { fg = "#88793c" },
    Typedef = { fg = "#88793c" },
    
    Special = { fg = "#6E93AC" },
    SpecialChar = { fg = "#6E93AC" },
    Tag = { fg = "#ab734b" },
    Delimiter = { fg = "#B4B2A8" },
    SpecialComment = { fg = "#636b67" },
    Debug = { fg = "#ab734b" },
    
    Title = { fg = "#6E93AC", bold = true },
    Bold = { bold = true },
    Italic = { italic = true },
    Underlined = { underline = true },
    Strike = { strikethrough = true },
    
    Error = { fg = "#ab734b" },
    Warning = { fg = "#88793c" },
    Info = { fg = "#6289A7" },
    Hint = { fg = "#6E93AC" },
    
    -- Git signs
    GitSignsAdd = { fg = "#8a7832" },
    GitSignsChange = { fg = "#88793c" },
    GitSignsDelete = { fg = "#ab734b" },
    
    -- Telescope
    TelescopeNormal = { fg = "#B4B2A8", bg = "#0d0808" },
    TelescopeBorder = { fg = "#6289A7", bg = "#0d0808" },
    TelescopePromptNormal = { fg = "#B4B2A8", bg = "#0d0808" },
    TelescopePromptBorder = { fg = "#6289A7", bg = "#0d0808" },
    TelescopeSelection = { fg = "#B4B2A8", bg = "#636b67" },
    TelescopeSelectionCaret = { fg = "#6289A7", bg = "#636b67" },
    
    -- Neotree
    NeoTreeNormal = { fg = "#B4B2A8", bg = "#0d0808" },
    NeoTreeNormalNC = { fg = "#B4B2A8", bg = "#0d0808" },
    NeoTreeFloatBorder = { fg = "#6289A7", bg = "#0d0808" },
    
    -- Statusline
    StatusLine = { fg = "#B4B2A8", bg = "#636b67" },
    StatusLineNC = { fg = "#636b67", bg = "#0d0808" },
    StatusLineFill = { bg = "#0d0808" },
    StatusLineMode = { fg = "#0d0808", bg = "#6289A7", bold = true },
    
    -- Tabline
    TabLine = { fg = "#B4B2A8", bg = "#0d0808" },
    TabLineFill = { bg = "#0d0808" },
    TabLineSel = { fg = "#0d0808", bg = "#6289A7" },
    
    -- WinBar
    WinBar = { fg = "#B4B2A8", bg = "#0d0808" },
    WinBarNC = { fg = "#636b67", bg = "#0d0808" },
    
    -- Pmenu
    Pmenu = { fg = "#B4B2A8", bg = "#636b67" },
    PmenuSel = { fg = "#0d0808", bg = "#6289A7" },
    PmenuSbar = { bg = "#636b67" },
    PmenuThumb = { bg = "#6289A7" },
    
    -- QuickFix
    QfTodo = { fg = "#88793c" },
    QfFile = { fg = "#6289A7" },
    
    -- Treesitter
    ["@comment"] = { fg = "#636b67", italic = true },
    ["@variable"] = { fg = "#B4B2A8" },
    ["@variable.builtin"] = { fg = "#ae6c38" },
    ["@constant"] = { fg = "#d69661" },
    ["@constant.builtin"] = { fg = "#d69661" },
    ["@string"] = { fg = "#8a7832" },
    ["@string.escape"] = { fg = "#6E93AC" },
    ["@number"] = { fg = "#d69661" },
    ["@boolean"] = { fg = "#d69661" },
    ["@type"] = { fg = "#88793c" },
    ["@type.builtin"] = { fg = "#88793c" },
    ["@attribute"] = { fg = "#6E93AC" },
    ["@function"] = { fg = "#6E93AC" },
    ["@function.builtin"] = { fg = "#6E93AC" },
    ["@function.call"] = { fg = "#6E93AC" },
    ["@keyword"] = { fg = "#ae6c38" },
    ["@keyword.function"] = { fg = "#ae6c38" },
    ["@keyword.operator"] = { fg = "#ae6c38" },
    ["@operator"] = { fg = "#6E93AC" },
    ["@punctuation"] = { fg = "#B4B2A8" },
    ["@punctuation.delimiter"] = { fg = "#B4B2A8" },
    ["@punctuation.bracket"] = { fg = "#B4B2A8" },
    ["@tag"] = { fg = "#ab734b" },
    ["@tag.attribute"] = { fg = "#6E93AC" },
    ["@tag.delimiter"] = { fg = "#B4B2A8" },
    ["@namespace"] = { fg = "#88793c" },
    ["@label"] = { fg = "#6289A7" },
    
    -- Diagnostic
    DiagnosticError = { fg = "#ab734b" },
    DiagnosticWarn = { fg = "#88793c" },
    DiagnosticInfo = { fg = "#6289A7" },
    DiagnosticHint = { fg = "#6E93AC" },
    DiagnosticUnderlineError = { sp = "#ab734b", underline = true },
    DiagnosticUnderlineWarn = { sp = "#88793c", underline = true },
    DiagnosticUnderlineInfo = { sp = "#6289A7", underline = true },
    DiagnosticUnderlineHint = { sp = "#6E93AC", underline = true },
    
    -- LSP
    LspReferenceText = { bg = "#636b67" },
    LspReferenceRead = { bg = "#636b67" },
    LspReferenceWrite = { bg = "#636b67" },
    LspSignatureActiveParameter = { bg = "#636b67" },
    
    -- Vim matchit
    MatchParen = { fg = "#0d0808", bg = "#6E93AC" },
    Search = { fg = "#0d0808", bg = "#88793c" },
    IncSearch = { fg = "#0d0808", bg = "#88793c" },
    Substitute = { fg = "#0d0808", bg = "#8a7832" },
}

-- Apply highlights
for group, opts in pairs(highlights) do
    vim.api.nvim_set_hl(0, group, opts)
end
