#!/bin/bash
if [[ "$1" == -* ]]; then
  brightnessctl set "${1#-}%-" >/dev/null
else
  brightnessctl set "${1}%" >/dev/null
fi
IFS="," read -r _ _ _ pct _ <<< "$(brightnessctl -m)"
percent="${pct%%%}"
qs -c desktop ipc call -- osd show "{\"icon\":\"brightness\",\"value\":$percent}"
