#!/bin/bash
action="$1"
if [ "$action" = "mute" ]; then
  wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle >/dev/null
else
  wpctl set-mute @DEFAULT_AUDIO_SINK@ 0 >/dev/null
  if [[ "$action" == +* ]]; then
    wpctl set-volume -l 1.0 @DEFAULT_AUDIO_SINK@ "${action#+}%+"
  elif [[ "$action" == -* ]]; then
    wpctl set-volume @DEFAULT_AUDIO_SINK@ "${action#-}%-"
  fi
fi

state=$(wpctl get-volume @DEFAULT_AUDIO_SINK@)
vol=${state#*Volume: }
vol=${vol%% *}

if [[ "$vol" =~ ([0-9]+)\.([0-9]+) ]]; then
  int=${BASH_REMATCH[1]}
  dec=${BASH_REMATCH[2]}
  dec="${dec}00"
  dec="${dec:0:2}"
  percent=$(( 100 * 10#$int + 10#$dec ))
else
  percent=0
fi

if [[ "$state" == *"MUTED"* ]] || [ "$percent" -eq 0 ]; then
  icon="volume-muted"
else
  icon="volume-high"
fi

qs -c desktop ipc call -- osd show "{\"icon\":\"$icon\",\"value\":$percent}"
(qs -c desktop ipc call audio refresh >/dev/null 2>&1 &)
